### ISSUE TITLE
Add custom response for errors

### ISSUE THREAD

**Issue by WastefulNick** [murar8/axum_typed_multipart#11]
https://github.com/murar8/axum_typed_multipart/blob/873751fdd7d03bf889d93c92431717233736a970/src/typed_multipart_error.rs#L52-L56

It would be nice to be able to customize the way `TypedMultipartError`s are handled, such as being able to return the error as JSON instead of raw text.

If you have any ideas of a good way to implement this I will happily make a PR if necessary :)

**Comment by murar8** [comment]
Yeah that makes perfect sense, I will take a look during the weekend to see how we could implement it, if you have a good idea please bring it up!
