### ISSUE TITLE
allow newtype idiom

### ISSUE THREAD

**Issue by ibotty** [murar8/axum_typed_multipart#52]
When I have e.g.

```
#[derive(Deserialize, TryFromMultipart)]
struct Form {
  test: MyNewtype,
}

struct MyNewtype(String)
```

It complains that `MyNewtype` does not implement `TryFromChunks`.  How can I use a newtype without writing a custom implementation?

**Comment by murar8** [comment]
Hi, the derive macro doesn't know how to transform a stream of data to a custom type so implementing `TryFromChunks` is unavoidable.

**Comment by murar8** [comment]
In this case the implementation would be really easy given that you can get the value by using `String::TryFromChunks` and wrap it.

**Comment by murar8** [comment]
For reference: https://docs.rs/axum_typed_multipart/latest/axum_typed_multipart/#custom-types
