### ISSUE TITLE
Why openssl as a build dependency?

### ISSUE THREAD

**Issue by stormshield-gt** [murar8/axum_typed_multipart#69]
In the [main Cargo.toml](https://github.com/murar8/axum_typed_multipart/blob/4809df854e25e71245d9600a606c7bcea5b288d7/Cargo.toml#L2) `openssl` is listed as a build dependency, but I can't find any _build.rs_ in this project. Am I missing something?

**Comment by murar8** [comment]
Hi, that was present because there was a build error when trying to compile using `-Z minimal-versions`, but I can see that's no longer the case.
