### ISSUE TITLE
Limit Vec lengh in request body

### ISSUE THREAD

**Issue by ChanManChan** [murar8/axum_typed_multipart#75]
#[form_data(field_name = "pic", limit = "5MiB")]
    pub pics: Vec<FieldData<NamedTempFile>>,

How do I limit the vec size here? I can't see the accepted form_data attributes. I want the vec size to be no more than 8.

**Comment by ChanManChan** [comment]
Thanks @murar8. I'm currently using the axum body limit as a work around. But it is not an elegant solution. I'll be looking forward to your new version. Thanks again. This is a very helpful crate.

**Comment by murar8** [comment]
@ChanManChan what do you think about using this crate? https://github.com/gengteng/axum-valid/tree/main?tab=readme-ov-file#-validatede-modifiede-validifiede-and-validifiedbyrefe 
The integration looks really nice and on second thought validation might be a bit out of scope for this crate.
