### ISSUE TITLE
Error with Vec<u8>

### ISSUE THREAD

**Issue by Cheban1996** [murar8/axum_typed_multipart#88]
I got error if type of field is `Vec<u8>`

`field 'bin' must be of type 'alloc::string::String': invalid utf-8 sequence of 1 bytes from index 0`

**Comment by murar8** [comment]
Hi @Cheban1996, can you provide some more context? Does it happen with a specific input? The u8 is parsed from its string representation in valid utf-8.

**Comment by Cheban1996** [comment]
> Hi @Cheban1996, can you provide some more context? Does it happen with a specific input? The u8 is parsed from its string representation in valid utf-8.

No, isn't utf-8
It's was just a binary file

**Comment by murar8** [comment]
Maybe https://docs.rs/axum_typed_multipart/latest/axum_typed_multipart/#large-uploads is what you want?

**Comment by Cheban1996** [comment]
> Maybe https://docs.rs/axum_typed_multipart/latest/axum_typed_multipart/#large-uploads is what you want?

Is not my way ((
Required to load in memory
But i resolve as this truble via Bytes :D
